apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
        track: stable
    spec:
      containers:
        - name: hello
          image: "mastoj/suavecore:v1.1"
          args: ["--ip", "0.0.0.0"]
          ports:
            - name: http
              containerPort: 8083
